spring.application.name=bucket-adapter
spring.config.import=optional:file:.env[.properties]
server.port=${SEREVER_PORT}
app.provider-implement=${PROVIDER_IMPL}
aws.region=eu-west-1xwxw
server.servlet.context-path=/api

spring.datasource.url=jdbc:mariadb://localhost:${MARIADB_PORT:3306}/${MARIADB_DATABASE:executor}
spring.datasource.username=${MARIADB_USER:executor}
spring.datasource.password=${MARIADB_PASSWORD:executor_pwd}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver