spring.application.name=bucket-adapter
spring.config.import=optional:file:.env[.properties]
server.port=${SERVER_PORT}
server.servlet.context-path=/api

spring.datasource.url=jdbc:${DB_DRIVER:mariadb}://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_DATABASE:executor}?sslMode=verify-full
spring.datasource.username=${DB_USER:executor}
spring.datasource.password=${DB_PASSWORD:executor_pwd}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
